### ISSUE TITLE
tab order should reflect workflow order

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/galaxy_tool_generator#11]

**Comment by MingChen0919** [comment]
You mean this order: 
**GTG Flowchart->Create Tool XML->Build Tool Repository->API Keys->Publish Tool Repository**?

The current one is:
**GTG Flowchart->Create Tool XML->API Keys->Build Tool Repository->Publish Tool Repository**?

**Comment by MingChen0919** [comment]
Does this look better?
<img width="965" alt="screen shot 2018-11-15 at 3 33 07 pm" src="https://user-images.githubusercontent.com/1262709/48579934-cb442700-e8eb-11e8-85ac-55d7df17024e.png">

I renamed the **API Keys** to **Connect to ToolShed**.

**Comment by bradfordcondon** [comment]
yeah i like that better.
