### ISSUE TITLE
blank mystery button  gives "page not found"

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/galaxy_tool_generator#12]
when editing the attributes of my root tool:

![screen shot 2018-11-15 at 10 33 37 am](https://user-images.githubusercontent.com/7063154/48563292-ffa2ed80-e8c1-11e8-821b-12b1cdb58738.png)

clicking it:

```
The requested page "/node/2/webform/components/new?render=overlay" could not be found.
```

**Comment by MingChen0919** [comment]
fix in PR #19 .
