### ISSUE TITLE
changes to the users guide put the detailed publishing steps before building the xml

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/galaxy_tool_generator#24]
everything after https://galaxy-tool-generator.readthedocs.io/en/latest/user_guide.html#build-tool-repository doesnt make sense.

Did this get moved because its common to all 3 methods?

If so thats fine, but it cant appear BEFORE the user reads how to build the XML.

Instead what you should do is have a final chapter in the user's guide called something like "Building the finished tool".   You want the reader to read that section AFTER they've built their XML tool, now they are ready to add non-xml files and publish.

**Comment by MingChen0919** [comment]
Yes, building tool repository is common to all three methods. I am confused. The 'build tool repository' IS after 'create tool XML'. Am I misunderstanding something here?

<img width="297" alt="screen shot 2018-11-16 at 8 38 31 am" src="https://user-images.githubusercontent.com/1262709/48624714-24a76700-e97b-11e8-9a63-2c0d6590dc39.png">

**Comment by bradfordcondon** [comment]
it occurs after it in the user_guide text on the sidebar.  however, someone reading your guide is liable to read past the "create tool xml" section and just keep reading the user guide.  see the below screenshot.

![screen shot 2018-11-16 at 8 41 03 am](https://user-images.githubusercontent.com/7063154/48624797-5e786d80-e97b-11e8-864d-804d3aababe5.png)



I'm working on a PR to fix, and arrange like so:


![screen shot 2018-11-16 at 8 41 38 am](https://user-images.githubusercontent.com/7063154/48624818-72bc6a80-e97b-11e8-99a6-f7497887d6e0.png)


See the difference?
