### ISSUE TITLE
Discrepancy between documentation and app

### ISSUE THREAD

**Issue by NicHerndon** [statonlab/galaxy_tool_generator#35]
I'm following the documentation on GTG on localhost (http://127.0.0.1:8089).

![screen shot 2018-11-28 at 3 04 54 pm](https://user-images.githubusercontent.com/4636279/49178952-3267cf80-f31f-11e8-8fff-c005b9ad8539.png)

After I created the XML file (**Use the Create Tool XML tab to start your XML file.**), I got redirected to http://127.0.0.1:8089/node/2/webform/components, where it seems I can update the XML components. However, the documentation indicates that I should go to the next tab to update the XML components (**Click edit for the XML file under the Build Tool Repository tab.**).

<img width="708" alt="screen shot 2018-11-27 at 8 05 07 pm" src="https://user-images.githubusercontent.com/4636279/49178997-50cdcb00-f31f-11e8-9b98-7d06451feedd.png">

Also, the form looks different when I click on the **Build Tool Repository** tab, and then **edit** the tool XML, due to the overlay.

<img width="719" alt="screen shot 2018-11-27 at 8 05 35 pm" src="https://user-images.githubusercontent.com/4636279/49179155-a3a78280-f31f-11e8-9c55-dd6c79bf7c28.png">

**Comment by bradfordcondon** [comment]
oops:  if you follow the full guide that should be more clear.  you get redirected to that components page on creation, but you'll need to navigate back there again, and thats how you do so.
